In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "mysql+pymysql://root:123456@localhost:3307/jobpulse"
)

In [3]:
df_salary = pd.read_csv(
    r"C:\Projects\JobPulse\data\cleaned\cleaned_salaries.csv"
)

df_salary.head()

,work_year,experience_level,employment_type,job_title,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,Executive Level,Full-Time,Head of Data,348516,United States,On-site,United States,M
1,2025,Executive Level,Full-Time,Head of Data,232344,United States,On-site,United States,M
2,2025,Senior Level,Full-Time,Data Scientist,145400,United States,On-site,United States,M
3,2025,Senior Level,Full-Time,Data Scientist,81600,United States,On-site,United States,M
4,2025,Mid Level,Full-Time,Engineer,160000,United States,Remote,United States,M

In [4]:
df_salary.to_sql(
    name="salaries",
    con=engine,
    if_exists="replace",
    index=False
)

print("Salary dataset uploaded successfully!")

Salary dataset uploaded successfully!

In [5]:
df_jobs = pd.read_csv(
    r"C:\Projects\JobPulse\data\cleaned\cleaned_job_postings.csv"
)

df_jobs.head()

,job_id,company_id,title,description,max_salary,med_salary,min_salary,formatted_work_type,location,formatted_experience_level,work_type,currency,compensation_type,salary_disclosed
0,85008768,0.0,Licensed Insurance Agent,While many industries were hurt by the last fe...,52000.0,52000.0,45760.0,Full-time,"Chico, CA",Not Specified,FULL_TIME,USD,BASE_SALARY,True
1,133114754,77766802.0,Sales Manager,Are you a dynamic and creative marketing profe...,NaN,NaN,NaN,Full-time,"Santa Clarita, CA",Not Specified,FULL_TIME,Unknown,Not Specified,False
2,133196985,1089558.0,Model Risk Auditor,Join Us as a Model Risk Auditor – Showcase You...,NaN,NaN,NaN,Contract,"New York, NY",Not Specified,CONTRACT,Unknown,Not Specified,False
3,381055942,96654609.0,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,NaN,NaN,NaN,Full-time,"Forney, TX",Not Specified,FULL_TIME,Unknown,Not Specified,False
4,529257371,1244539.0,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,NaN,NaN,NaN,Full-time,"New York, NY",Not Specified,FULL_TIME,Unknown,Not Specified,False

In [6]:
df_jobs.to_sql(
    name="job_postings",
    con=engine,
    if_exists="replace",
    index=False
)

print("Job postings uploaded successfully!")

Job postings uploaded successfully!

In [7]:
df_companies = pd.read_csv(
    r"C:\Projects\JobPulse\data\cleaned\cleaned_companies.csv"
)

df_industries = pd.read_csv(
    r"C:\Projects\JobPulse\data\cleaned\cleaned_company_industries.csv"
)

df_skills = pd.read_csv(
    r"C:\Projects\JobPulse\data\cleaned\cleaned_job_skills.csv"
)

In [8]:
df_companies.to_sql(
    name="companies",
    con=engine,
    if_exists="replace",
    index=False
)

print("Companies table loaded successfully!")

Companies table loaded successfully!

In [9]:
df_industries.to_sql(
    name="company_industries",
    con=engine,
    if_exists="replace",
    index=False
)

print("Company industries table loaded successfully!")

Company industries table loaded successfully!

In [10]:
df_skills.to_sql(
    name="job_skills",
    con=engine,
    if_exists="replace",
    index=False
)

print("Job skills table loaded successfully!")

Job skills table loaded successfully!